import { compile } from "json-schema-to-typescript";
import { writeFileSync, mkdirSync } from "fs";
import { dirname, join } from "path";

const SCHEMA_URL = "https://w3c.github.io/mnx/docs/mnx-schema.json";
const OUTPUT_DIR = join(import.meta.dir, "../src/spec");
const SCHEMA_FILE = join(OUTPUT_DIR, "mnx-schema.json");
const TYPES_FILE = join(OUTPUT_DIR, "mnx-types.ts");

async function sync() {
    console.log(`Downloading MNX Schema from ${SCHEMA_URL}...`);

    let schema: any;
    try {
        const res = await fetch(SCHEMA_URL);
        if (!res.ok) throw new Error(`Failed to fetch schema: ${res.statusText}`);

        schema = await res.json();

        // Ensure directory exists
        mkdirSync(OUTPUT_DIR, { recursive: true });

        // Save raw schema
        console.log(`Saving schema to ${SCHEMA_FILE}...`);
        writeFileSync(SCHEMA_FILE, JSON.stringify(schema, null, 2));
    } catch (error) {
        console.error("Error downloading MNX spec:", error);
        process.exit(1);
    }

    try {
        // Generate Types
        console.log(`Generating TypeScript interfaces to ${TYPES_FILE}...`);
        const ts = await compile(schema, "MNX", {
            bannerComment: "/* eslint-disable */\n/**\n * This file was automatically generated by json-schema-to-typescript.\n */",
            ignoreMinAndMaxItems: true, // Often helps with tuple validation issues
            unknownAny: false // Default to any for unknown types
        });

        writeFileSync(TYPES_FILE, ts);
        console.log("TypeScript types generated successfully!");
    } catch (error) {
        console.error("Warning: Failed to generate TypeScript types from schema.");
        console.error("This is likely due to complex JSON Schema features not fully supported by the generator.");
        console.error("You can still use the raw 'mnx-schema.json' for validation.");
        console.error("Error details:", error);
        // Do not exit with error, as we successfully downloaded the schema
    }
}

sync();
